# Generated by Django 4.2.4 on 2023-10-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationapp', '0002_delete_assign_evaluation_delete_create_evaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='question_bank',
            name='Name',
        ),
        migrations.AddField(
            model_name='question_bank',
            name='Trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluationapp.trainer'),
            preserve_default=False,
        ),
    ]
