# Generated by Django 4.2.4 on 2023-08-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=50)),
                ('Address1', models.CharField(max_length=50)),
                ('Address2', models.CharField(max_length=50)),
                ('Address3', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Website', models.CharField(max_length=50)),
                ('Logo', models.FileField(blank=True, null=True, upload_to='upload_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Master_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Value', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branche', models.CharField(max_length=50)),
                ('Branchcode', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.district')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.state')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.CharField(max_length=50)),
                ('Startdate', models.DateField()),
                ('Enddate', models.DateField()),
                ('Branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.branche')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.course')),
                ('Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.trainer')),
            ],
        ),
    ]
