# Generated by Django 4.2.4 on 2023-10-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master_Data',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='Batch',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='branche',
            old_name='Branche',
            new_name='branche',
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
